# Generated by Django 5.1.5 on 2025-06-07 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_remove_hod_department_name_hod_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='DOJ',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Experince',
            field=models.IntegerField(default=-2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='contact_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_number', 'year')},
        ),
    ]
