# Generated by Django 5.1.5 on 2025-06-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0003_faculty_doj_faculty_experince_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='Experince',
        ),
    ]
