# Generated by Django 5.1.5 on 2025-06-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0004_remove_faculty_experince'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='status',
            field=models.BooleanField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='pending'),
        ),
    ]
