# Generated by Django 5.1.5 on 2025-06-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0005_subject_semester_alter_attendancereport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(default=4, max_length=10),
            preserve_default=False,
        ),
    ]
