# Generated by Django 5.1.5 on 2025-06-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0006_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='reviewed_by_HOD',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentresult',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
