# Generated by Django 5.1.5 on 2025-06-09 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0007_studentresult_reviewed_by_hod_studentresult_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CMS.faculty'),
            preserve_default=False,
        ),
    ]
