# Generated by Django 5.1.5 on 2025-06-09 09:03

from email.policy import default
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0008_studentresult_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(default='00:00:00', null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20),
        ),
    ]
